# Generated by Django 3.1.2 on 2020-12-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='cost_center',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='employee_dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='product',
            field=models.IntegerField(),
        ),
    ]
