# Generated by Django 3.1.2 on 2020-12-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/img'),
        ),
    ]
